# version: '3.7'

# services:
#   disxt-test-api:
#     container_name: api
#     # image: node:'11.15.0'
#     build: ./
#     command: npm run dev
#     working_dir: /usr/src/gdoc-api

#     ports: 
#       - "4000:4000"
#     links:
#       - mongoDb
#     volumes:
#       - ./:/usr/src/gdoc-api
#       - /usr/src/gdoc-api/node_modules/

#   mongoDb:
#     container_name: mongo
#     image: mongo
#     ports:
#       - "27017:27017"


