version: '3.7'

services:
  disxt-test-api:
    container_name: api
    build: ./
    command: npm run dev
    working_dir: /usr/src/disxt-api

    ports: 
      - "4000:4000"
    links:
      - mongoDb
    volumes:
      - ./:/usr/src/disxt-api
      - /usr/src/disxt-api/node_modules/

  mongoDb:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"


